version: '3.8'
services:
  # mariadb:
  #   image: mydb:inception
  #   build:
  #     context: requirements/mariadb
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - inception
  nginx:
    image: mywebserver:inception
    build:
      context: requirements/nginx
    ports:
      - "8080:443"
    networks:
      - inception

networks:
  inception:
    driver: bridge
