version: '3.8'

services:
  mariadb:
    build:
      context: requirements/mariadb
    networks:
      - mynet
    volumes:
      - dbvol:/var/lib/mysql
    restart: always
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWD
      - DB_HOST

  wordpress:
    build:
      context: requirements/wordpress
    networks:
      - mynet
    volumes:
      - wpvol:/var/www/html
    depends_on:
      - mariadb
    restart: always
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWD
      - DB_HOST
      - WP_ADMIN_PASSWD
      - WP_USER_PASSWD

  nginx:
    build:
      context: requirements/nginx
    networks:
      - mynet
    volumes:
      - wpvol:/var/www/html
    depends_on:
      - wordpress
    restart: always
    ports:
      - "443:443"

networks:
  mynet:
    name: mynet
    driver: bridge

volumes:
  wpvol:
    name: wpvol
    driver_opts:
      type: none
      device: /home/sunwsong/data/wpvol
      o: bind
  dbvol:
    name: dbvol
    driver_opts:
      type: none
      device: /home/sunwsong/data/dbvol
      o: bind
