version: '3.8'
services:
  mariadb:
    build:
      context: requirements/mariadb
    networks:
      - mybridge
    volumes:
     - /home/sunwsong/data:/etc/mysql
    stdin_open: true #tmp
    tty: true #tmp

  wordpress:
    build:
      context: requirements/wordpress
    networks:
      - mybridge
    volumes:
     - /home/sunwsong/data:/var/www/html
    depends_on:
      - mariadb
    stdin_open: true #tmp
    tty: true #tmp

  nginx:
    build:
      context: requirements/nginx
    networks:
      - mybridge
    volumes:
     - /home/sunwsong/data:/var/www/html
    ports:
      - "8080:443"
    depends_on:
      - wordpress
    stdin_open: true #tmp
    tty: true #tmp

networks:
  mybridge:
    driver: bridge

volumes:
  myvol:
  dbvol: