version: '3.8'
services:
  # mariadb:
  #   image: mydb:inception
  #   build:
  #     context: requirements/mariadb
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - inception
  nginx:
    image: nginx:sunwsong
    build:
      context: requirements/nginx
    ports:
      - "8080:443"
    networks:
      - mybridge
    volumes:
      - myvol:/var/www/html
    stdin_open: true #tmp
    tty: true #tmp

  wordpress:
    image: mywp
    build:
      context: requirements/wordpress
    networks:
      - mybridge
    volumes:
      - myvol:/var/www/html
    stdin_open: true #tmp
    tty: true #tmp

networks:
  mybridge:
    driver: bridge

volumes:
  myvol:
